### ISSUE TITLE
Updated merger with new atlas links don't work

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/VisuAlign#57]
Apparently the atlas is not recognized... says "undefined"

http://cmbn-navigator.uio.no/navigator/filmstripzoom/filmstripzoom.html?atlas=undefined&series=5255&preview=WHSRatv2Preview.png

I have used an xml from QNII anchored to WHSv2 named "H441_TimmThionin_horizontal_IR_gjeldende_US" located here: X:\hbp-02421\0000_FINAL-Timm-Thionin\H441\QNII_anchoring

**Comment by Tevemadar** [comment]
Applied a fix with the new assumption that N3 expects "Short atlas name" from https://github.com/Neural-Systems-at-UIO/Navigator/wiki/Atlas-naming-convention

**Comment by Majpuc** [comment]
Still "undefined" in the atlas field e.g. H441a

**Comment by Tevemadar** [comment]
Navigator bug. Manually modified 841_2785_5255_H441a_Timm_dark_horizontal_s001 (first section in H441a) to v2, and then it opened (single-section LZ). Let @darwinjob know.

**Comment by darwinjob** [comment]
> Applied a fix with the new assumption that N3 expects "Short atlas name" from https://github.com/Neural-Systems-at-UIO/Navigator/wiki/Atlas-naming-convention

I don't like assumptions :) I believed we have agreed on the short atlas names, haven't we? @Tevemadar what did you expect/prefer? We still can change this...

**Comment by Tevemadar** [comment]
@darwinjob short atlas names are fine with me. From the top of my head I'm not sure if it has been discussed what `anchored_to` field will contain after the update.

**Comment by darwinjob** [comment]
> Navigator bug. Manually modified 841_2785_5255_H441a_Timm_dark_horizontal_s001 (first section in H441a) to v2, and then it opened (single-section LZ). Let @darwinjob know.

Apparently N3 generates LZ links with "undefined" if the atlas is WHS Rat v3. If I manually set the id to 200100 everything works http://cmbn-navigator.uio.no/navigator/filmstripzoom/filmstripzoom.html?atlas=200100&series=5255&preview=WHSRatv2Preview.png
It a typo :) somewhere, should be easy to fix.

**Comment by darwinjob** [comment]
> @darwinjob short atlas names are fine with me. From the top of my head I'm not sure if it has been discussed what `anchored_to` field will contain after the update.

I made the changes in https://github.com/Neural-Systems-at-UIO/Navigator/wiki/Atlas-naming-convention
BTW how do I allow others to edit the table in this GitHub of yours ;)

**Comment by darwinjob** [comment]
@Tevemadar 
I've fixed this here:
`meta.innerHTML=ouv.name+"<br>"+cfg.Width.toString()+" x "+cfg.Height.toString()+"<br>"
                        +JSON.parse('{"100000":"ABA Mouse CCFv2","200000":"WHS Rat v2","300000":"ABA Mouse CCFv3_2015", "300100":"ABA Mouse CCFv3_2017", "200100":"WHS Rat v3"}')[args.atlas]
                        +"<br><a href='http://cmbn-navigator.uio.no/navigator/feeder/original/?id="+section_id+"' target='_blank'>Download image</a>";
                meta.style.left=window.innerWidth-meta.scrollWidth-5+"px";`

What's about this one?

`function meshview(){
                var wnd=window.open("about:blank","meshview");
                var d=wnd.document;
                d.write("<html><head><title>MeshView export</title><style>textarea{width:100%;height:80%}</style></head><body>");
                d.write("Please copy the coordinates below into <a href='http://www.nesys.uio.no/MeshGen/MeshView.html?bitlas="
                    +JSON.parse('{"100000":"ABAMouseHier","200000":"WHSRatV2","300000":"ABAv3-Hier"}')[args.atlas]
                    +".bitlas' target='_blank'>MeshView</a>. Viewer needs Adobe Flash.");
                if(args.atlas==="100000")d.write("<br>(Hint: \"Basic cell groups and regions\" is the gray wrapper structure to be switched off)");
                if(args.atlas==="300000")d.write("<br>(Hint: \"root\" is the gray wrapper structure to be switched off)");
                d.write("<textarea id='ta'>");
                d.write("RGB 0 0 1\n");
                d.write("SCALE 5");
                switch(args.atlas){
                    case "200000":
                    case "300000":
                        meshmarkers.forEach(function(item){
                            d.write("\n"+item.x.toFixed(0)+" "+item.y.toFixed(0)+" "+item.z.toFixed(0));
                        });
                        break;
                    case "100000":
                        meshmarkers.forEach(function(item){
                            d.write("\n"+item.x.toFixed(0)+" "+(item.y-528).toFixed(0)+" "+(item.z-320).toFixed(0));
                        });
                }
                d.write("</textarea></body></html>");
                d.close();
            }`

**Comment by Tevemadar** [comment]
@darwinjob Cool, LZ in Navigator is properly updated then. MeshView export is for the Flash-based MeshView, which has no updated atlases, and the identifiers are the ones which are in the code. So exporting will need a larger rework in order to point to the new version.

While this editor does not show it, markdown for multiline code blocks is to prepend them by four spaces. The backquotes thing makes format `inline` and drops the whitespace.

    `multiline block
    with spaces in front`

The same without spaces (linebreak disappears, backquotes are consumed for the code-formatting itself):

`multiline block
without spaces in front`

**Comment by Majpuc** [comment]
Still not working... @Tevemadar 
can you have a look at these two links: http://cmbn-navigator.uio.no/navigator/filmstripzoom/filmstripzoom.html?atlas=undefined&series=5256&preview=WHSRatv2Preview.png
http://cmbn-navigator.uio.no/navigator/filmstripzoom/filmstripzoom.html?atlas=undefined&series=5255&preview=WHSRatv2Preview.png

**Comment by darwinjob** [comment]
Yeah, I’m on it, I just need to deploy the new version. This requires a restart but we have a teaching session taking place.


On 4 May 2020, at 10:45, Majpuc <notifications@github.com> wrote:

﻿

Still not working... @Tevemadar<https://github.com/Tevemadar>
can you have a look at these two links: http://cmbn-navigator.uio.no/navigator/filmstripzoom/filmstripzoom.html?atlas=undefined&series=5256&preview=WHSRatv2Preview.png
http://cmbn-navigator.uio.no/navigator/filmstripzoom/filmstripzoom.html?atlas=undefined&series=5255&preview=WHSRatv2Preview.png

**Comment by Majpuc** [comment]
Hi Dmitri,

Okay, thanks!

Maja ☺

**Comment by darwinjob** [comment]
Fixed

**Comment by Majpuc** [comment]
Validated 24.09.2020
